export const WORKEXES = [
  {
    title: "Member, Tech",
    startDate: "June 2025",
    endDate: "Present",
    techStack: ["Python", "React.js", "Git", "Redis", "Mongo DB", "Postgresql"],
    description: [
      "Developed live dashboard for displaying real-time post trade data, enabling traders to monitor and analyze trades efficiently.",
    ],
    organisation: "D.E. Shaw India Private Limited",
    type: "Full Time Role",
    links: [],
  },
  {
    title: "Software Development Engineer I",
    startDate: "July 2024",
    endDate: "May 2025",
    techStack: [
      "Python",
      "Sanic",
      "asyncio",
      "React.js",
      "REST API",
      "Kubernetes",
      "Postman",
      "Docker",
      "AWS",
      "Git",
      "SQS",
      "Redis",
      "S3",
      "Mongo DB",
      "Postgresql",
    ],
    description: [
      "Designed and implemented code for generating pdf-based complete medical summary report and pipe-seperated data file for leads comprising of 200+ parameters. The report generation is done using the same DLS based product which is explained below. For the result of various parameters, rule engine is used.",
      "Architected and laid down the framework for DLS based product, controlling UI using database and configurations which reduced releases by 40% saving 4 hours of weekly developer time. Used low-level design patterns like factory, singleton, and strategy.",
      "Developed a custom rule engine which facilitates the insurance decision without human intervention. It also has a frontend interface for the operations team to create and manage rules.",
      "Improved efficiency of a graph-based algorithm from O(n^2) to O(n) reducing API response time to genereate Medical Reports by 50%.",
    ],
    organisation: "Tata 1MG",
    type: "Full Time Role",
    links: [],
  },
  {
    title: "Software Developer",
    startDate: "August 2022",
    endDate: "June 2024",
    techStack: [
      "Django Rest",
      "Python",
      "Postgresql",
      "Next.js",
      "REST API",
      "React.js",
      "Pandas",
      "Nginx",
      "Framework",
      "Git",
    ],
    description: [
      "Developed Official Website of BITS Pilani Library migrating data from old website to new website. Also included a CMS for the library staff to update the website without changes in code.",
      "Integrated features like Space booking in library, Requesting for books and articles, Online catalogue, Chatbot, and a unique Three search feature for universal search of books, research papers etc.",
      "Used the cache feature of Next.js to reduce the load time of the webpages and integrated it with django to revalidate the cache only when the data is changed.",
      "Also developed BHG Gallery website for the library to showcase the art and culture of BITS Pilani. Integrated components like heritage books, videos and images.",
    ],
    organisation: "Library BITS Pilani",
    type: "Part-time",
    links: [
      ["Library Website", "https://library.bits-pilani.ac.in/"],
      ["BHG Gallery", "https://library.bits-pilani.ac.in/bhg"],
    ],
  },
  {
    title: "Software Developer",
    startDate: "May 2023",
    endDate: "July 2023",
    techStack: [
      "Spring boot",
      "Java",
      "Oracle DB",
      "React.js",
      "REST API",
      "Scrum",
      "JUnit",
      "Mockito",
      "Postman",
    ],
    description: [
      "As a Summer Internship Oppurtunity, engineered a proof-of-concept software reducing manual work of lookup of 150+ fields in account opening flow.",
      "Also enhanced the core functionality of utility library to compare two XML files using Java and tested the same using JUnit and mockito by creating robust test cases.",
      "Pipelined API development, documentation and testing through postman collections automated with newman and python subprocesses.",
    ],
    organisation: "Standard Chartered GBS",
    type: "Internship",
    links: [],
  },
];
